### ISSUE TITLE
Definição de Metodologia

### ISSUE THREAD

**Issue by esmsena** [Requisitos-de-Software/2023.2-E-Titulo#3]
---
name: Definição de Metodologia com Scrum Adaptável
about: Definição da metodologia de desenvolvimento adaptável utilizando o framework Scrum.
title: 'Definição de Metodologia com Scrum Adaptável'
labels: 'Metodologia, Scrum'
assignees: '@Madu01'

## Descrição
Esta issue tem como objetivo a definição da metodologia de desenvolvimento adaptável com base no framework Scrum. A adaptação do Scrum à nossa realidade é crucial para o sucesso do projeto, garantindo uma abordagem ágil e flexível.

### Tarefas
- [x] Identificar os princípios-chave do Scrum que podem ser aplicados ao projeto.
- [x] Adaptar as cerimônias do Scrum (reuniões diárias, revisão de sprint, retrospectiva, etc.) de acordo com as necessidades do projeto.
- [x] Definir os papéis e responsabilidades dentro da equipe de projeto adaptada.
- [x] Desenvolver uma estratégia de acompanhamento e adaptação contínua da metodologia.

### Critérios de Aceitação
- [x] A metodologia adaptada com base no Scrum está documentada de forma clara e concisa.
- [x] A adaptação do Scrum está alinhada com as necessidades específicas do projeto.
- [x] Os papéis e responsabilidades estão definidos de maneira precisa.
- [x] Os critérios de priorização e gestão do backlog estão estabelecidos.
- [x] Uma estratégia de acompanhamento contínuo da metodologia está descrita.

### Informações Adicionais
Esta issue foi atribuída a @Madu01 . Certifique-se de revisar e concluir a tarefa dentro do prazo estabelecido. Qualquer dúvida, não hesite em buscar apoio da equipe ou dos Scrum Masters experientes.

**Comment by Madu01** [comment]
Acabei de atualizar

**Comment by esmsena** [comment]
**Resumo:**
- Foram feitas as seguintes alterações: [definição da metodologia de desenvolvimento adaptável com base no framework Scrum adapitavel]

**Commits e Pull Requests Relacionados:**
- [[Link para a metodologia](https://github.com/Requisitos-de-Software/2023.2-E-Titulo/blob/feature-metodologia/metodologia.md) ]

Agradeço a todos os colaboradores envolvidos nesta tarefa! A issue está agora concluída e pode ser fechada.
