### ISSUE TITLE
Artefato Cenários

### ISSUE THREAD

**Issue by jvcostta** [Requisitos-de-Software/2023.2-e-Titulo#48]
# Descrição
    Esta issue visa a criação do artefato de Cenários.

# Tarefas
    Checklist de ações que devem ser 

- [x] Criar tópicos de intro (introdução, objetivos, metodologia)
- [x]  Fazer os cenários dos requisitos com prioridade mais alta, baseando-se em algum método de priorização
- [x] Detalhar cada item dos cenários

# Critérios de Aceitação
 
- [x] Tópicos de introdução autoexplicativos
- [x] Concluir a criação dos cenários

**Comment by MateusPy** [comment]
Tudo implementado corretamente
