### ISSUE TITLE
esqueleto dos artefatos

### ISSUE THREAD

**Issue by esmsena** [Requisitos-de-Software/2023.2-E-Titulo#5]
---
name: Criação do Esqueleto de Artefatos Documentais
about: Tarefa para criar um esqueleto dos artefatos documentais do projeto.
title: 'Criação do Esqueleto de Artefatos Documentais'
labels: 'Documentação'
assignees: '@Madu01 @EduardaSMarques'

## Descrição
Esta issue tem como objetivo criar um esqueleto dos artefatos documentais para o projeto. Ter um conjunto estruturado de artefatos é fundamental para manter a documentação organizada, facilitar a colaboração e garantir a rastreabilidade das informações essenciais.

### Tarefas
- [x] Definir uma estrutura padrão para cada tipo de artefato, incluindo títulos, seções e formatos recomendados.
- [x] Criar modelos ou templates para os artefatos mais comuns, tornando mais fácil a sua criação e preenchimento.
- [x] Documentar as diretrizes de nomenclatura e organização dos artefatos.

### Critérios de Aceitação
- [x] Um esqueleto dos artefatos documentais foi criado e está disponível para a equipe.
- [x] A estrutura padrão para cada tipo de artefato está definida de forma clara.
- [x] Os modelos ou templates para os artefatos mais comuns estão prontos para uso.
- [x] As diretrizes de nomenclatura e organização dos artefatos estão documentadas.
- [x] O esqueleto dos artefatos foi revisado e aprovado pela equipe.

### Informações Adicionais
Esta issue foi atribuída a @Madu01 @EduardaSMarques. Certifique-se de revisar e concluir a tarefa dentro do prazo estabelecido. Se surgirem dúvidas durante o processo de criação do esqueleto dos artefatos, não hesite em buscar orientação da equipe ou de especialistas em documentação.

**Comment by Madu01** [comment]
Já concluí, tive que mudar umas coisas na issue, pois não precisava

**Comment by esmsena** [comment]
**Resumo:**
- Foram feitas as seguintes alterações: [Criar um esqueleto dos artefatos documentais para o projeto.]

**Commits Relacionados:**
- [[Link para o commit](https://github.com/Requisitos-de-Software/2023.2-E-Titulo/blob/feature-metodologia/esqueletoArtefatos)]

Agradeço a todos os colaboradores envolvidos nesta tarefa! A issue está agora concluída e pode ser fechada.

**Comment by esmsena** [comment]
**Resumo:**
- Foram feitas as seguintes alterações: [Criar um esqueleto dos artefatos documentais para o projeto.]

**Commits Relacionados:**
- [[Link para o commit](https://github.com/Requisitos-de-Software/2023.2-E-Titulo/blob/feature-metodologia/esqueletoArtefatos)]

Agradeço a todos os colaboradores envolvidos nesta tarefa! A issue está agora concluída e pode ser fechada.
