### ISSUE TITLE
Artefato NFR

### ISSUE THREAD

**Issue by Madu01** [Requisitos-de-Software/2023.2-e-Titulo#51]
# Descrição
Será criado o artefato NFR.

# Tarefas

- [x] Criar esqueleto do artefato de modo a seguir o padrão
- [x] Criar conteúdo em cada tópico do artefato

# Critérios de Aceitação
Definir os critérios para a issue ser considerada concluída.

- [ ] Concluir as tarefas
- [x] Terminar o artefato

**Comment by MateusPy** [comment]
Tudo certo !
