### ISSUE TITLE
Backward From

### ISSUE THREAD

**Issue by Maryyscreuza** [Requisitos-de-Software/2023.2-e-Titulo#78]
# Descrição

Essa issue serve para documentar o artefato de backward from, utilizado na pós-rastreabilidade.

# Tarefas

Checklist de ações que devem ser realizadas.

- [x] Adição de introdução, objetivo e metodologia no artefato
- [x] Tabela de todos os requisitos funcionais elicitados no projeto
- [x] Tabela de todos os requisitos não-funcionais elicitados no projeto
- [x]  Descrição e preenchimento dos elos funcionais e não-funcionais
- [x] Histórico de versões atualizado

# Critérios de Aceitação

- [x] Todas as tabelas foram preenchidas com os requisitos e sua devida rastreabilidade
- [x] Nas tabelas tem se o requisito foi implementado ou não 
- [x] Os elos estão preenchidos e são coerentes

**Comment by jvcostta** [comment]
Tudo devidamente implementado. Issue fechada com sucesso
